log_file	"~/.config/mpd/log"
music_directory    "~/Músicas"
pid_file           "~/.config/mpd/pid"
db_file            "~/.config/mpd/database"
sticker_file       "~/.config/mpd/sticker"
auto_update "no"
restore_paused "yes"

audio_output {
        type            "pulse"
        name            "MPD"
}
audio_output {
   type   "fifo"
   name   "Visualizer"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}
